# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import jsonfield2.fields
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protoLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtefactCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('containerArt', models.ForeignKey(related_name='artefactcomposition_set', to='rai01ref.Artefact')),
                ('inputArt', models.ForeignKey(related_name='+', to='rai01ref.Artefact')),
                ('outputArt', models.ForeignKey(blank=True, related_name='+', to='rai01ref.Artefact', null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactSource',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(blank=True, to='rai01ref.Artefact', null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('baseType', models.CharField(default='string', blank=True, choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], max_length=50, null=True)),
                ('prpLength', models.IntegerField(blank=True, null=True)),
                ('prpScale', models.IntegerField(blank=True, null=True)),
                ('vType', models.CharField(default='string', blank=True, choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], max_length=50, null=True)),
                ('prpDefault', models.CharField(blank=True, max_length=50, null=True)),
                ('prpChoices', models.TextField(blank=True, null=True)),
                ('isRequired', models.BooleanField(default=False)),
                ('isSensitive', models.BooleanField(default=False)),
                ('crudType', models.CharField(blank=True, choices=[('storeOnly', 'No se presentan nunca (los id, jsonTypes, etc )'), ('readOnly', 'No se guarda nunca (usado por reglas de gestion)'), ('insertOnly', 'No se actualiza (un campo absorbido al momento de la creacion, ej:direccion de envio'), ('updateOnly', 'Al insertar nulo o VrDefault, (estado inicial fijo)')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('document', models.CharField(choices=[('ARTEFACT', 'ARTEFACT'), ('CAPACITY', 'CAPACITY'), ('REQUIREMENT', 'REQUIREMENT')], max_length=11)),
                ('dtype', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtefact',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.ForeignKey(to='rai01ref.Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(to='rai01ref.Domain')),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('docType', models.ForeignKey(blank=True, related_name='+', to='rai01ref.DocType', null=True)),
                ('domain', models.ForeignKey(blank=True, related_name='+', to='rai01ref.Domain', null=True)),
                ('refRequirement', models.ForeignKey(blank=True, related_name='+', to='rai01ref.Requirement', null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smRegStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, max_length=50, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('smVersion', models.CharField(default='0', editable=False, max_length=50, null=True, blank=True)),
                ('code', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True)),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='requirement',
            field=models.ForeignKey(to='rai01ref.Requirement'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='docType',
            field=models.ForeignKey(blank=True, to='rai01ref.DocType', null=True),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='docType',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.DocType', null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='domain',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.Domain', null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='refCapacity',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.Capacity', null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactsource',
            name='source',
            field=models.ForeignKey(blank=True, to='rai01ref.Source', null=True),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='requirement',
            field=models.ForeignKey(to='rai01ref.Requirement'),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='capacity',
            field=models.ForeignKey(to='rai01ref.Capacity'),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='docType',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.DocType', null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='domain',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.Domain', null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='refArtefact',
            field=models.ForeignKey(blank=True, related_name='+', to='rai01ref.Artefact', null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy', null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together=set([('docType', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='projet',
            unique_together=set([('domain', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together=set([('projet', 'requirement')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectcapacity',
            unique_together=set([('projet', 'capacity')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectartefact',
            unique_together=set([('artefact', 'projet')]),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='doctype',
            unique_together=set([('document', 'dtype')]),
        ),
        migrations.AlterUniqueTogether(
            name='docattribute',
            unique_together=set([('docType', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='capacity',
            unique_together=set([('docType', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactsource',
            unique_together=set([('source', 'artefact')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactrequirement',
            unique_together=set([('artefact', 'requirement')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactcapacity',
            unique_together=set([('artefact', 'capacity')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefact',
            unique_together=set([('docType', 'code')]),
        ),
    ]
