# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import uuid
import jsonfield2.fields
import taggit.managers
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('protoLib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('graphLevel', models.IntegerField(blank=True, default=0, null=True)),
                ('grphMode', models.IntegerField(blank=True, default=0, null=True)),
                ('graphForm', models.IntegerField(blank=True, default=0, null=True)),
                ('showPrpType', models.BooleanField(default=False)),
                ('showBorder', models.BooleanField(default=False)),
                ('showFKey', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiagramEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('diagram', models.ForeignKey(to='prototype.Diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('dbName', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('modelPrefix', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dbEngine', models.CharField(choices=[('sqlite3', 'sqlLite3'), ('postgres', 'Postgress'), ('mysql', 'mySQL')], max_length=20, default='sqlite3', null=True, blank=True)),
                ('dbName', models.CharField(blank=True, max_length=200, null=True)),
                ('dbUser', models.CharField(blank=True, max_length=200, null=True)),
                ('dbPassword', models.CharField(blank=True, max_length=200, null=True)),
                ('dbHost', models.CharField(blank=True, max_length=200, null=True)),
                ('dbPort', models.CharField(blank=True, max_length=200, null=True)),
                ('smCreatedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('baseType', models.CharField(choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], max_length=50, default='string', null=True, blank=True)),
                ('prpLength', models.IntegerField(blank=True, null=True)),
                ('prpScale', models.IntegerField(blank=True, null=True)),
                ('prpDefault', models.CharField(blank=True, max_length=50, null=True)),
                ('prpChoices', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('isLookUpResult', models.BooleanField(default=False)),
                ('isNullable', models.BooleanField(default=False)),
                ('isRequired', models.BooleanField(default=False)),
                ('isReadOnly', models.BooleanField(default=False)),
                ('isForeign', models.BooleanField(default=False, editable=False)),
                ('vType', models.CharField(choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], max_length=50, default='string', null=True, blank=True)),
                ('isSensitive', models.BooleanField(default=False)),
                ('isEssential', models.BooleanField(default=False)),
                ('crudType', models.CharField(choices=[('storeOnly', 'No se presentan nunca (los id, jsonTypes, etc )'), ('readOnly', 'No se guarda nunca (usado por reglas de gestion)'), ('insertOnly', 'No se actualiza (un campo absorbido al momento de la creacion, ej:direccion de envio'), ('updateOnly', 'Al insertar nulo o VrDefault, (estado inicial fijo)')], max_length=20, null=True, blank=True)),
                ('dbName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEquivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProtoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('entity', models.ForeignKey(to='prototype.Entity')),
                ('smCreatedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('smNaturalCode', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smRegStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smWflowStatus', models.CharField(blank=True, max_length=50, editable=False, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(blank=True, max_length=50, editable=False, null=True, default='0')),
                ('code', models.CharField(max_length=200, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metaDefinition', jsonfield2.fields.JSONField(blank=True, null=True)),
                ('entity', models.ForeignKey(related_name='prototype_set', to='prototype.Entity')),
                ('smCreatedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, parent_link=True, to='prototype.Property', serialize=False, primary_key=True)),
                ('relatedName', models.CharField(blank=True, max_length=50, null=True)),
                ('baseMin', models.CharField(blank=True, max_length=50, null=True)),
                ('baseMax', models.CharField(blank=True, max_length=50, null=True)),
                ('refMin', models.CharField(blank=True, max_length=50, null=True)),
                ('refMax', models.CharField(blank=True, max_length=50, null=True)),
                ('onRefDelete', models.CharField(choices=[('CASCADE', 'Cascade deletes; the default'), ('PROTECT', 'Prevent deletion of the referenced object by raising ProtectedError, a subclass of django.db.IntegrityError'), ('SET_NULL', 'Set the ForeignKey null; this is only possible if null is True'), ('SET_DEFAULT', 'Set the ForeignKey to its default value; a default for the ForeignKey must be set.  @function si possible'), ('DO_NOTHING', 'Use default Db constraint')], max_length=50, null=True, blank=True)),
                ('typeRelation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('prototype.property',),
        ),
        migrations.AddField(
            model_name='propertyequivalence',
            name='sourceProperty',
            field=models.ForeignKey(related_name='sourcePrp', blank=True, null=True, to='prototype.Property'),
        ),
        migrations.AddField(
            model_name='propertyequivalence',
            name='targetProperty',
            field=models.ForeignKey(related_name='targetPrp', blank=True, null=True, to='prototype.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='entity',
            field=models.ForeignKey(related_name='property_set', to='prototype.Entity'),
        ),
        migrations.AddField(
            model_name='property',
            name='smCreatedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='smModifiedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='smOwningTeam',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='property',
            name='smOwningUser',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='project',
            field=models.ForeignKey(to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='model',
            name='smCreatedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='smModifiedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='smOwningTeam',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='model',
            name='smOwningUser',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='smTags',
            field=taggit.managers.TaggableManager(through='taggit.TaggedItem', verbose_name='Tags', blank=True, help_text='A comma-separated list of tags.', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='entity',
            name='model',
            field=models.ForeignKey(related_name='entity_set', to='prototype.Model'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smCreatedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='smModifiedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='smOwningTeam',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smOwningUser',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='entity',
            field=models.ForeignKey(to='prototype.Entity'),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smCreatedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smModifiedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smOwningTeam',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smOwningUser',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagram',
            name='project',
            field=models.ForeignKey(to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smCreatedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smModifiedBy',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smOwningTeam',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smOwningUser',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='refEntity',
            field=models.ForeignKey(null=True, to='prototype.Entity', related_name='refEntity_set'),
        ),
        migrations.AlterUniqueTogether(
            name='prototype',
            unique_together=set([('entity', 'code', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='propertyequivalence',
            unique_together=set([('sourceProperty', 'targetProperty', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('entity', 'code', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('code', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('project', 'code', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('model', 'code', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='diagramentity',
            unique_together=set([('diagram', 'entity', 'smOwningTeam', 'smVersion')]),
        ),
        migrations.AlterUniqueTogether(
            name='diagram',
            unique_together=set([('project', 'code', 'smOwningTeam', 'smVersion')]),
        ),
    ]
