# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protoLib', '0002_usercontext_smversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodageNormalise',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomaineAffaires',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('id_domaine_affaires', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementDonnee',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_element_donnee', models.CharField(max_length=200)),
                ('numero_elem_cn', models.CharField(max_length=200, blank=True, null=True)),
                ('type_de_base', models.CharField(max_length=200, blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('element_transforme', models.TextField(blank=True, null=True)),
                ('gabarit', models.CharField(max_length=200, blank=True, null=True)),
                ('element_transmis', models.CharField(max_length=200, blank=True, null=True)),
                ('domaine_valeurs', models.TextField(blank=True, null=True)),
                ('date_entree_vigueur', models.DateField(blank=True, null=True)),
                ('date_derniere_modification', models.DateField(blank=True, null=True)),
                ('consignes_saisie', models.TextField(blank=True, null=True)),
                ('pratiques_acceptees', models.TextField(blank=True, null=True)),
                ('validation_sur_element', models.TextField(blank=True, null=True)),
                ('validations_inter_elements', models.TextField(blank=True, null=True)),
                ('validations_inter_enregistrement', models.TextField(blank=True, null=True)),
                ('requis_par', models.CharField(max_length=200, blank=True, null=True)),
                ('historique', models.BooleanField(default=False)),
                ('cle_etrangere', models.BooleanField(default=False)),
                ('cle_primaire', models.BooleanField(default=False)),
                ('longueur', models.CharField(max_length=200, blank=True, null=True)),
                ('obligation', models.CharField(max_length=200, blank=True, null=True)),
                ('mode_attribution', models.CharField(max_length=200, blank=True, null=True)),
                ('provenance_reference', models.TextField(blank=True, null=True)),
                ('exceptions', models.TextField(blank=True, null=True)),
                ('statut_element', models.CharField(max_length=200, blank=True, null=True)),
                ('si_provenance', models.CharField(max_length=200, blank=True, null=True)),
                ('methode_transfert', models.CharField(max_length=200, blank=True, null=True)),
                ('contexte_particulier', models.TextField(blank=True, null=True)),
                ('reference_foire_questions', models.TextField(blank=True, null=True)),
                ('element_provenance', models.TextField(blank=True, null=True)),
                ('methode_transformation', models.CharField(max_length=200, blank=True, null=True)),
                ('date_trans_bdm', models.DateField(blank=True, null=True)),
                ('type_mode_attribution', models.CharField(max_length=200, blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('elements_de_source', models.TextField(blank=True, null=True)),
                ('volumetrie', models.CharField(max_length=200, blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_entite', models.CharField(max_length=200)),
                ('description_entite', models.TextField(blank=True, null=True)),
                ('historique', models.BooleanField(default=False)),
                ('physical_name', models.CharField(max_length=200, blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexDesDonnees',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_donnee', models.CharField(max_length=200)),
                ('definition_donnee', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_modele', models.CharField(max_length=200)),
                ('idModel', models.CharField(max_length=200, blank=True)),
                ('idRef', models.CharField(max_length=200, blank=True)),
                ('type_modele', models.CharField(max_length=200, blank=True, null=True)),
                ('version_modele', models.CharField(max_length=200, blank=True, null=True)),
                ('auteur_modele', models.CharField(max_length=200, blank=True, null=True)),
                ('nom_si_bdm', models.CharField(max_length=200, blank=True, null=True)),
                ('document_reference', models.CharField(max_length=200, blank=True, null=True)),
                ('acronyme_si_bdm', models.CharField(max_length=200, blank=True, null=True)),
                ('date_doc_reference', models.CharField(max_length=200, blank=True, null=True)),
                ('version_doc_reference', models.CharField(max_length=200, blank=True, null=True)),
                ('description_modele', models.TextField(blank=True, null=True)),
                ('date_creation_modele', models.DateField(blank=True, null=True)),
                ('date_derniere_modif_modele', models.DateField(blank=True, null=True)),
                ('physical_name', models.CharField(max_length=200, blank=True, null=True)),
                ('acteur_principal', models.CharField(max_length=200, blank=True, null=True)),
                ('autres_acteurs', models.CharField(max_length=200, blank=True, null=True)),
                ('intrants_declencheurs', models.CharField(max_length=200, blank=True, null=True)),
                ('domaff_modele', models.ForeignKey(to='rai00base.DomaineAffaires', related_name='modele_domaff_modele')),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeleRaccordement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_modele_raccordement', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_modrac1', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_modrac2', models.CharField(max_length=200, blank=True, null=True)),
                ('notes_modele_raccordement', models.TextField(blank=True, null=True)),
                ('mod_modrac1', models.ForeignKey(to='rai00base.Modele', related_name='modele_raccordement_mod_modrac1', blank=True, null=True)),
                ('mod_modrac2', models.ForeignKey(to='rai00base.Modele', related_name='modele_raccordement_mod_modrac2', blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('tmp_domaff', models.ForeignKey(to='rai00base.DomaineAffaires', blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('code_norme', models.CharField(max_length=200)),
                ('nom_norme', models.CharField(max_length=200, blank=True, null=True)),
                ('notes_norme', models.CharField(max_length=200, blank=True, null=True)),
                ('version_norme', models.CharField(max_length=200, blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PorteeRegleGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('eledon_portee', models.ForeignKey(to='rai00base.ElementDonnee', related_name='portee_regle_gestion_eledon_portee')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_projet', models.CharField(max_length=200)),
                ('description_projet', models.TextField(blank=True, null=True)),
                ('domaff_projet', models.ForeignKey(to='rai00base.DomaineAffaires', related_name='projet_domaff_projet')),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raccordement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('no_raccordement', models.IntegerField()),
                ('tmp_rac1', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_rac2', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_alias', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_destt', models.CharField(max_length=200, blank=True, null=True)),
                ('eledon_rac1', models.ForeignKey(to='rai00base.ElementDonnee', related_name='set_eledon_rac1', blank=True, null=True)),
                ('eledon_rac2', models.ForeignKey(to='rai00base.ElementDonnee', related_name='set_eledon_rac2', blank=True, null=True)),
                ('modrac_rac', models.ForeignKey(to='rai00base.ModeleRaccordement', related_name='raccordement_modrac_rac', blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglesGestion',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('id_regles_gestion', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('eledon_regles', models.ForeignKey(to='rai00base.ElementDonnee', related_name='regles_gestion_eledon_regles')),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegroupementDesModeles',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('mod_regrou', models.ForeignKey(to='rai00base.Modele', related_name='regroupement_des_modeles_mod_regrou')),
                ('projet_regro', models.ForeignKey(to='rai00base.Projet', related_name='regroupement_des_modeles_projet_regro')),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('dependance', models.BooleanField(default=False)),
                ('tmp_foreign', models.CharField(max_length=200, blank=True, null=True)),
                ('tmp_alias', models.CharField(max_length=200, blank=True, null=True)),
                ('nom_relation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('baseMin', models.CharField(max_length=50, blank=True, null=True)),
                ('baseMax', models.CharField(max_length=50, blank=True, null=True)),
                ('refMin', models.CharField(max_length=50, blank=True, null=True)),
                ('refMax', models.CharField(max_length=50, blank=True, null=True)),
                ('entite_rela1', models.ForeignKey(to='rai00base.Entite', related_name='relation_entite_rela1')),
                ('entite_rela2', models.ForeignKey(to='rai00base.Entite', related_name='relation_entite_rela2')),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('nom_specification', models.CharField(max_length=200)),
                ('gabarit', models.CharField(max_length=200, blank=True, null=True)),
                ('longueur', models.CharField(max_length=200, blank=True, null=True)),
                ('type_de_base', models.CharField(max_length=200, blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=200, blank=True, null=True)),
                ('uri_source', models.CharField(max_length=200, blank=True, null=True)),
                ('domaine_valeurs_spec', models.TextField(blank=True, null=True)),
                ('norme_spec', models.ForeignKey(to='rai00base.Norme', related_name='specifications_norme_spec', blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRegle',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smVersion', models.CharField(max_length=50, editable=False, default='0', blank=True, null=True)),
                ('code_type_regle', models.CharField(max_length=200)),
                ('description_type', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smModifiedBy', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
                ('smOwningTeam', models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True)),
                ('smOwningUser', models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reglesgestion',
            name='typere_regges',
            field=models.ForeignKey(to='rai00base.TypeRegle', related_name='regles_gestion_typere_regges', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porteereglegestion',
            name='portee_regles',
            field=models.ForeignKey(to='rai00base.ReglesGestion', related_name='portee_regle_gestion_portee_regles', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porteereglegestion',
            name='smCreatedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porteereglegestion',
            name='smModifiedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porteereglegestion',
            name='smOwningTeam',
            field=models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porteereglegestion',
            name='smOwningUser',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexdesdonnees',
            name='spec_index',
            field=models.ForeignKey(to='rai00base.Specifications', related_name='index_des_donnees_spec_index', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entite',
            name='entite_mod',
            field=models.ForeignKey(to='rai00base.Modele', related_name='entite_entite_mod'),
        ),
        migrations.AddField(
            model_name='entite',
            name='smCreatedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entite',
            name='smModifiedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entite',
            name='smOwningTeam',
            field=models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entite',
            name='smOwningUser',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='eledon_index',
            field=models.ForeignKey(to='rai00base.IndexDesDonnees', related_name='element_donnee_eledon_index', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='eledon_spec',
            field=models.ForeignKey(to='rai00base.Specifications', related_name='element_donnee_eledon_spec', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='entite_elem',
            field=models.ForeignKey(to='rai00base.Entite', related_name='element_donnee_entite_elem'),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='smCreatedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='smModifiedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='smOwningTeam',
            field=models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdonnee',
            name='smOwningUser',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='codnor_inddon',
            field=models.ForeignKey(to='rai00base.IndexDesDonnees', related_name='codage_normalise_codnor_inddon', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='codnor_norme',
            field=models.ForeignKey(to='rai00base.Norme', related_name='codage_normalise_codnor_norme', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='codnor_spec',
            field=models.ForeignKey(to='rai00base.Specifications', related_name='codage_normalise_codnor_spec', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='smCreatedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='smModifiedBy',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='smOwningTeam',
            field=models.ForeignKey(to='protoLib.TeamHierarchy', editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codagenormalise',
            name='smOwningUser',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, editable=False, related_name='+', blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='typeregle',
            unique_together=set([('code_type_regle',)]),
        ),
        migrations.AlterUniqueTogether(
            name='specifications',
            unique_together=set([('nom_specification',)]),
        ),
        migrations.AlterUniqueTogether(
            name='regroupementdesmodeles',
            unique_together=set([('mod_regrou', 'projet_regro')]),
        ),
        migrations.AlterUniqueTogether(
            name='reglesgestion',
            unique_together=set([('eledon_regles', 'id_regles_gestion')]),
        ),
        migrations.AlterUniqueTogether(
            name='projet',
            unique_together=set([('domaff_projet', 'nom_projet')]),
        ),
        migrations.AlterUniqueTogether(
            name='porteereglegestion',
            unique_together=set([('eledon_portee',)]),
        ),
        migrations.AlterUniqueTogether(
            name='norme',
            unique_together=set([('code_norme',)]),
        ),
        migrations.AlterUniqueTogether(
            name='indexdesdonnees',
            unique_together=set([('nom_donnee',)]),
        ),
        migrations.AlterUniqueTogether(
            name='domaineaffaires',
            unique_together=set([('id_domaine_affaires',)]),
        ),
    ]
