
CREATE TABLE "protoExt_customdefinition"
CREATE TABLE "protoExt_parameters"
CREATE TABLE "protoExt_viewdefinition"

CREATE TABLE "protoLib_entitymap"
CREATE TABLE "protoLib_logger"
CREATE TABLE "protoLib_teamhierarchy"
CREATE TABLE "protoLib_usercontext"
CREATE TABLE "protoLib_userprofile"

CREATE TABLE "prototype_diagram"
CREATE TABLE "prototype_diagramentity"
CREATE TABLE "prototype_entity"
CREATE TABLE "prototype_model"
CREATE TABLE "prototype_project"
CREATE TABLE "prototype_property"
CREATE TABLE "prototype_propertyequivalence"
CREATE TABLE "prototype_prototable"
CREATE TABLE "prototype_prototype"
CREATE TABLE "prototype_relationship" 

CREATE TABLE "rai00base_codagenormalise"
CREATE TABLE "rai00base_domaineaffaires"
CREATE TABLE "rai00base_elementdonnee"
CREATE TABLE "rai00base_entite"
CREATE TABLE "rai00base_indexdesdonnees"
CREATE TABLE "rai00base_modele"
CREATE TABLE "rai00base_modeleraccordement"
CREATE TABLE "rai00base_norme"
CREATE TABLE "rai00base_porteereglegestion"
CREATE TABLE "rai00base_projet"
CREATE TABLE "rai00base_raccordement"
CREATE TABLE "rai00base_reglesgestion"
CREATE TABLE "rai00base_regroupementdesmodeles"
CREATE TABLE "rai00base_relation"
CREATE TABLE "rai00base_specifications"
CREATE TABLE "rai00base_typeregle"

CREATE TABLE "rai01ref_artefact"
CREATE TABLE "rai01ref_artefactcapacity"
CREATE TABLE "rai01ref_artefactcomposition"
CREATE TABLE "rai01ref_artefactrequirement"
CREATE TABLE "rai01ref_artefactsource"
CREATE TABLE "rai01ref_capacity"
CREATE TABLE "rai01ref_docattribute"
CREATE TABLE "rai01ref_doctype"
CREATE TABLE "rai01ref_domain"
CREATE TABLE "rai01ref_projectartefact"
CREATE TABLE "rai01ref_projectcapacity"
CREATE TABLE "rai01ref_projectrequirement"
CREATE TABLE "rai01ref_projet"
CREATE TABLE "rai01ref_requirement"
CREATE TABLE "rai01ref_source"

