CREATE TABLE "rai01ren_doctype" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "document" varchar(11) NOT NULL,
    "dtype" varchar(200) NOT NULL,
    "category" varchar(50) NULL,
    "notes" text NULL,
    "description" text NULL, UNIQUE ("document",
    "dtype"));
;
CREATE TABLE "rai01ren_docattribute" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "docType_id" integer NOT NULL REFERENCES "rai01ren_doctype" ("id"),
    "code" varchar(200) NOT NULL,
    "baseType" varchar(50) NULL,
    "prpLength" integer NULL,
    "prpScale" integer NULL,
    "vType" varchar(50) NULL,
    "prpDefault" varchar(50) NULL,
    "prpChoices" text NULL,
    "isRequired" bool NOT NULL,
    "isSensitive" bool NOT NULL,
    "crudType" varchar(20) NULL,
    "description" text NULL, UNIQUE ("docType_id",
    "code"));
;
CREATE TABLE "rai01ren_domain" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "code" varchar(200) NOT NULL,
    "description" text NULL, UNIQUE ("code"));
;
CREATE TABLE "rai01ren_artefact" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "docType_id" integer NOT NULL REFERENCES "rai01ren_doctype" ("id"),
    "code" varchar(200) NOT NULL,
    "domain_id" integer NULL REFERENCES "rai01ren_domain" ("id"),
    "description" text NULL,
    "info" text NOT NULL,
    "refArtefact_id" integer NULL REFERENCES "rai01ren_artefact" ("id"), UNIQUE ("docType_id",
    "code"));
;
CREATE TABLE "rai01ren_capacity" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "docType_id" integer NOT NULL REFERENCES "rai01ren_doctype" ("id"),
    "code" varchar(200) NOT NULL,
    "domain_id" integer NULL REFERENCES "rai01ren_domain" ("id"),
    "description" text NULL,
    "info" text NOT NULL,
    "refCapacity_id" integer NULL REFERENCES "rai01ren_capacity" ("id"), UNIQUE ("docType_id",
    "code"));
;
CREATE TABLE "rai01ren_requirement" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "docType_id" integer NOT NULL REFERENCES "rai01ren_doctype" ("id"),
    "code" varchar(200) NOT NULL,
    "domain_id" integer NULL REFERENCES "rai01ren_domain" ("id"),
    "description" text NULL,
    "info" text NOT NULL,
    "refRequirement_id" integer NULL REFERENCES "rai01ren_requirement" ("id"), UNIQUE ("docType_id",
    "code"));
;
CREATE TABLE "rai01ren_source" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "code" varchar(200) NOT NULL,
    "reference" varchar(200) NULL,
    "notes" text NULL,
    "description" text NULL, UNIQUE ("code"));
;
CREATE TABLE "rai01ren_artefactsource" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "source_id" integer NULL REFERENCES "rai01ren_source" ("id"),
    "artefact_id" integer NULL REFERENCES "rai01ren_artefact" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("source_id",
    "artefact_id"));
;
CREATE TABLE "rai01ren_artefactcomposition" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "containerArt_id" integer NOT NULL REFERENCES "rai01ren_artefact" ("id"),
    "inputArt_id" integer NOT NULL REFERENCES "rai01ren_artefact" ("id"),
    "outputArt_id" integer NULL REFERENCES "rai01ren_artefact" ("id"),
    "condition" text NULL,
    "notes" text NULL,
    "description" text NULL);
CREATE TABLE "rai01ren_artefactrequirement" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "artefact_id" integer NOT NULL REFERENCES "rai01ren_artefact" ("id"),
    "requirement_id" integer NOT NULL REFERENCES "rai01ren_requirement" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("artefact_id",
    "requirement_id"));
;
CREATE TABLE "rai01ren_artefactcapacity" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "artefact_id" integer NOT NULL REFERENCES "rai01ren_artefact" ("id"),
    "capacity_id" integer NOT NULL REFERENCES "rai01ren_capacity" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("artefact_id",
    "capacity_id"));
;
CREATE TABLE "rai01ren_projet" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "domain_id" integer NOT NULL REFERENCES "rai01ren_domain" ("id"),
    "code" varchar(200) NOT NULL,
    "notes" text NULL,
    "description" text NULL, UNIQUE ("domain_id",
    "code"));
;
CREATE TABLE "rai01ren_projectartefact" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "projet_id" integer NOT NULL REFERENCES "rai01ren_projet" ("id"),
    "artefact_id" integer NOT NULL REFERENCES "rai01ren_artefact" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("artefact_id",
    "projet_id"));
;
CREATE TABLE "rai01ren_projectcapacity" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "projet_id" integer NOT NULL REFERENCES "rai01ren_projet" ("id"),
    "capacity_id" integer NOT NULL REFERENCES "rai01ren_capacity" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("projet_id",
    "capacity_id"));
;
CREATE TABLE "rai01ren_projectrequirement" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "smNaturalCode" varchar(50) NULL,
    "smRegStatus" varchar(50) NULL,
    "smWflowStatus" varchar(50) NULL,
    "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"),
    "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"),
    "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"),
    "smCreatedOn" datetime NULL,
    "smModifiedOn" datetime NULL,
    "smUUID" char(32) NOT NULL,
    "projet_id" integer NOT NULL REFERENCES "rai01ren_projet" ("id"),
    "requirement_id" integer NOT NULL REFERENCES "rai01ren_requirement" ("id"),
    "notes" text NULL,
    "description" text NULL, UNIQUE ("projet_id",
    "requirement_id"));
;
