# -*- coding: utf-8 -*-

DATA_MENU_TEST = {
    "text": "prototype",
    "qtip": "",
    "qtitle": "",
    "iconCls": "",
    "id": "protoMenu-ext-gen1448",
    "index": 0,
    "expanded": True,
    "children": [{
        "text": "Relationship",
        "qtip": "",
        "qtitle": "",
        "iconCls": "icon-1",
        "id": "protoMenu-ext-gen1449",
        "index": 0,
        "expanded": False,
        "children": [],
        "leaf": True,
        "viewCode": "prototype.Relationship"
    }, {
        "text": "Entity",
        "qtip": "",
        "qtitle": "",
        "iconCls": "icon-1",
        "id": "protoMenu-ext-gen1450",
        "index": 1,
        "expanded": False,
        "children": [],
        "leaf": True,
        "viewCode": "prototype.Entity"
    }, {
        "text": "Property",
        "qtip": "",
        "qtitle": "",
        "iconCls": "icon-1",
        "id": "protoMenu-ext-gen1451",
        "index": 2,
        "expanded": False,
        "children": [],
        "leaf": True,
        "viewCode": "prototype.Property"
    }, {
        "text": "Project",
        "qtip": "",
        "qtitle": "",
        "iconCls": "icon-1",
        "id": "protoMenu-ext-gen1452",
        "index": 3,
        "expanded": False,
        "children": [],
        "leaf": True,
        "viewCode": "prototype.Project"
    }, {
        "text": "Model",
        "qtip": "",
        "qtitle": "",
        "iconCls": "icon-1",
        "id": "protoMenu-ext-gen1453",
        "index": 4,
        "expanded": False,
        "children": [],
        "leaf": True,
        "viewCode": "prototype.Model"
    }],
    "leaf": False,
    "viewCode": "protoMenu-ext-gen4397"
}